config/routes.rb
Fitmonday::Application.routes.draw do

  get "search/search_user"

  get "highscore/test"
  get "highscore/show"

  match '/auth/:provider/callback', :to => 'sessions#create_social_login'
  match '/auth/failure', :to => 'sessions#failure'

  get "goalaccepter/accept_goal"
  get "goalupdater/update_goal"
  post "goalaccepter/accept_goal"
  post "goalupdater/update_goal"

  get "auth/login"
  get "auth/logout"
  post "auth/login"
  get "auth/newuser"
  post "auth/signup_new_user"
  
  resources :users
  resources :goals
  

  root :to => 'goals#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  ROLE_USER = 1
  ROLE_ADMIN = 2

  attr_accessible :first_name, :last_name, :num_of_steps, :password, :username
  attr_accessible :password_confirmation, :role, :provider, :uid

  attr_accessible :image
  mount_uploader :image, ImageUploader

  has_many :goals, :dependent=>:destroy

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true, :uniqueness => true
  #validates :password, :presence => true, :confirmation => true
  #validates :username, :uniqueness => true
  validates :password, :confirmation => true
  
  def self.create_with_fb_omniauth(auth_hash)
    create! do |user|
        user.provider = auth_hash["provider"]
        user.uid = auth_hash["uid"]
        user.username = auth_hash["info"]["nickname"]
        user.first_name = auth_hash["info"]["first_name"]
        user.last_name = auth_hash["info"]["last_name"]
    end
  end
  
  def self.create_with_google_omniauth(auth_hash)
    create! do |user|
        user.provider = auth_hash["provider"]
        user.uid = auth_hash["uid"]
        user.username = auth_hash["info"]["email"]
        user.first_name = auth_hash["info"]["first_name"]
        user.last_name = auth_hash["info"]["last_name"]
        user.remote_image_url = auth_hash["info"]["image"]
    end
  end
  
  def self.create_new_user(newuser_hash)
    create! do |user|
        user.first_name = newuser_hash["first_name"]
        user.last_name = newuser_hash["last_name"]
        user.username = newuser_hash["username"]
        user.password = newuser_hash["password"]
    end
  end

  def get_total_steps_so_far
    total_goals = 0
    goals.each do |goal|
       total_goals += goal.num_of_steps_so_far
    end
    total_goals
  end
  
  def self.search(search)
    if search
      where('first_name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
  def is_admin?
    !!(role == ROLE_ADMIN)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_user_self_or_admin, :only => [:edit, :update, :destroy]
  before_filter :authorize_admin, :only => [:new, :create]
  helper_method :user_self_or_admin?

  def authorize_user_self_or_admin
    if !user_self_or_admin? 
      flash[:error] = 'The action is only allowed for the user him/ herself.'
      redirect_to :back
    end
  end

  def user_self_or_admin?
    user_session = User.find(session[:user_id])
    user_param = User.find(params[:id])
    user_session and user_param and 
      ((user_session.id == user_param.id) or user_session.role==User::ROLE_ADMIN)
  end
  
  def authorize_admin
    if !is_admin?
      flash[:error] = 'The action is only allowed for admin.'
      redirect_to :back
    end
  end
  
  def is_admin?
    user_session = User.find(session[:user_id])
    user_session and user_session.role==User::ROLE_ADMIN
  end
  
  # GET /users
  # GET /users.json
  def index
    
    if params[:search]
      @users = User.search(params[:search])
    else
      @users = User.all(:order=>"first_name ASC")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end
  
  def newuser
    @user = User.new
    
    respond_to do |format|
      format.html # newuser.html.erb
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
  			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  			<ul>
  			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
  			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.text_field :first_name, :placeholder=>'First Name', :size=>10 %>
		<%= f.text_field :last_name, :placeholder=>'Last Name', :size=>10 %>
	</div>
	<div class="field">
		<%= f.text_field :username, :placeholder=>'Username', :size=>25 %>
	</div>
	<div class="field">
		<%= f.password_field :password, :placeholder=>'Password', :size=>25 %>
	</div>
	<div class="field">
		<%= f.password_field :password_confirmation, :placeholder=>'Re-enter Password', :size=>25 %>
	</div>
    <div class="field">
    	Profile picture:
    	<%= f.file_field :image %>
    </div>
	<br />
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h4>Editing user</h4>
	
	<%= render 'form' %>
	
	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>

</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "container">

	<div style="float:left">
		<h4>Friends (<%=@users.count%>)</h4>
	</div>
	
	<%
	user = User.find_by_id(session[:user_id])
	if !session[:user_id].nil? && user.is_admin? 
	%>
		<div style="float:right">
	  		<button type="button" class="btn btn-success btn-xs"> 
				<%= link_to 'New User', new_user_path, :class=>'btnlink-white' %>
			</button>
	  	</div>
	<%
	end 
	%>
	
	<!--
	<form id="friends_search_form"> 
		<input type="text" name="search" />
	</form>
	-->
	
	<div class="row" id="user-wall">
		<% @users.each do |user| %>
			<% if user.image? %>
	        	<%= link_to image_tag(user.image_url, :class => 'profile-image profile-img-userindex'), 
	            	user, :class=>'profile-image-link', 'data-toggle'=>'tooltip', 'data-title'=>user.first_name + " " + user.last_name %>
	        <% else %>
				<%= link_to image_tag('nopic.jpg', :class => 'profile-image profile-img-tooltip profile-img-userindex'), 
	            	user, :class=>'profile-image-link', 'data-toggle'=>'tooltip', 'data-title'=>user.first_name + " " + user.last_name %>
	        <% end %>
		<% end %>	
	</div>
	
	<% 
	if !session[:user_id].nil? && user.is_admin? && user.username=='rarusli' %>
		<% @users.each do |user| %>
		    <%=link_to '(' + user.first_name + " " + user.last_name + ')', user%>
		    <%=link_to 'Edit', edit_user_path(user)%>
		    <%=link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }%>
		    <br />
		<% end %>
	<% end %>
	
</div>

app/views/users/new.html.erb
<div class="container">
	<h4>New user</h4>

	<%= render 'form' %>
	
	<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">	
    <div class="row">
        <div class="col-md-1 col-md-2 profile-image-userprofile-container">
     		<% if @user.image? %>
	        	<%= image_tag @user.image_url, :class=>'profile-image-userprofile img-circle' %>
	        <% else %>
				<%= image_tag 'nopic.jpg', :class=>'profile-image-userprofile img-circle' %>
	        <% end %>
       	</div>
        <div style="float:left;padding:5px;text-align:center">
        	<%= @user.goals.count %><br /><h5>Goals</h5>
        </div>
        <div style="float:left;padding:5px;text-align:center">
        	<%=number_with_delimiter(@user.get_total_steps_so_far, delimiter:",")%><br /><h5>Steps</h5>
        </div>
    </div>
    
    <h4><%= @user.first_name %> <%=@user.last_name%></h4>

    <% @user.goals.each do |goal| %>
      <%
         #link_to 'Show', goal %>
      <%
         #link_to 'Edit', edit_goal_path(goal) %>
      <%
         #link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %>

     <% if goal.accept == 1 %>
      	<% if goal.num_of_steps_so_far >= goal.num_of_steps %>
        	<div class="row pretty-row finished-row">
        <% else %>
        	<div class="row pretty-row inprogress-row">
        <% end %>
      <% elsif goal.accept == 0 %>
      	<div class="row pretty-row rejected-row">
      <% else %>
        <div class="row pretty-row">
      <% end %>
        <div class="col-sm-4">
            <strong>"<%= link_to goal.name, edit_goal_path(goal) %>"</strong>
            <% if goal.accept == 1 %>
                <% if goal.num_of_steps_so_far.is_a? Integer %>
                    (<%=goal.num_steps_so_far_formatted%>/<%= goal.num_steps_formatted%> steps)
                <% else %>
                    (0/<%=goal.num_steps_formatted%> steps)
                <% end %>
            <% end %>
          <br />
          <% if goal.user_id == goal.challenger_id %>
            Individual challenge
          <% else %>
            <%=User.find_by_id(goal.challenger_id).first_name%>'s challenge
          <% end %>
          <br />
          <% if goal.accept == 1 %>
            <% if goal.num_of_steps_so_far >= goal.num_of_steps %>
                Goals Completed! - <%= time_ago_in_words(goal.updated_at) %> ago
            <% else %>
                In Progress - <%= time_ago_in_words(goal.updated_at) %> ago
                <%
                	percent_reached_so_far = goal.percent_reached_so_far
                	color_class = "progress-bar"
                	if percent_reached_so_far <= 25
                		color_class = "progress-bar progress-bar-danger"
                	elsif percent_reached_so_far <= 50
                		color_class = "progress-bar progress-bar-warning"
                	elsif percent_reached_so_far <= 75
                		color_class = "progress-bar progress-bar-info"
                	else
                		color_class = "progress-bar progress-bar-success"
                	end
               	%>
               	
                <div class="progress">
  					<div class="<%=color_class%>" role="progressbar" aria-valuenow="<%percent_reached_so_far%>" 
  						aria-valuemin="0" aria-valuemax="100" style="width:<%=percent_reached_so_far%>%;">
  						<%=percent_reached_so_far%> %
  					</div>
				</div>
            <% end %>
          <% elsif goal.accept == 0 %>
            Goal Rejected! - <%= time_ago_in_words(goal.updated_at) %> ago
          <% else %>
            <button type = "button" class="btn btn-primary btn-xs">
                  <%= link_to "Accept",
                    { :controller => 'goalaccepter',
                      :action => 'accept_goal',
                      :goal_id => goal.id,
                      :accept => 1 },
                    :method => 'POST',
                    :class=> 'btnlink-white'
                %>
            </button>
            <button type = "button" class="btn btn-danger btn-xs">
                <%= link_to "Reject",
                    { :controller => 'goalaccepter',
                      :action => 'accept_goal',
                      :goal_id => goal.id,
                      :accept => 0 },
                    :method => 'POST',
                    :class=> 'btnlink-white'
                %>
            </button>
            <br /><br />
          <% end %>
          	
        
          
        </div>
      </div>
      </tr>

  	<% end %>

    <br />
    <% if user_self_or_admin? %>
    	<%= link_to 'Edit', edit_user_path(@user) %> |
    <% end %>
    <%= link_to 'Back', users_path %>

</div>