config/routes.rb
Fitmonday::Application.routes.draw do

  get "search/search_user"

  get "highscore/test"
  get "highscore/show"

  match '/auth/:provider/callback', :to => 'sessions#create_social_login'
  match '/auth/failure', :to => 'sessions#failure'

  get "goalaccepter/accept_goal"
  get "goalupdater/update_goal"
  post "goalaccepter/accept_goal"
  post "goalupdater/update_goal"

  get "auth/login"
  get "auth/logout"
  post "auth/login"
  get "auth/newuser"
  post "auth/signup_new_user"
  
  resources :users
  resources :goals
  

  root :to => 'goals#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  require 'active_support/core_ext'
  
  attr_accessible :accept, :amount_of_transaction, :challenger_id, :charity_id,
  :confirm_to_charity, :date_of_transaction, :dollars_pledge, :goaltype_id, :name, :num_of_steps, :num_of_steps_so_far, :user_id, :updated_at

  belongs_to :user
  belongs_to :charity
  belongs_to :goaltype

  validates :user_id, :presence => true
  validates :challenger_id, :presence => true
  validates :name, :presence => true
  validates :num_of_steps, :presence => true
  
  before_save :default_values
  
  def default_values
    self.num_of_steps_so_far ||= 0
  end
  
  def percent_reached_so_far
    (num_of_steps_so_far.to_f/ num_of_steps)*100
  end
  
  def num_steps_formatted
    number_with_delimiter(num_of_steps, delimiter:",")
  end
  
  def num_steps_so_far_formatted
    number_with_delimiter(num_of_steps_so_far, delimiter:",")
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authorize_user_self_or_admin, :only => [:edit, :update, :destroy]
  helper_method :user_self?

  def authorize_user_self_or_admin
    if !user_self_or_admin? 
      flash[:error] = 'The action is only allowed to the user him/ herself.'
      redirect_to :back
    end
  end

  def user_self_or_admin?
    goal = Goal.find(params[:id])
    user_session = User.find(session[:user_id])
    user_param_id = goal.user_id
    user_session and user_param_id and 
      ((user_session.id == user_param_id) or user_session.role==User::ROLE_ADMIN)
  end
  
  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all(:order=>"updated_at DESC")
    @goals_acceptedOrRejected = Goal.where("accept=1 or accept=0").order("updated_at DESC")
    @goals_notYetAcceptedOrRejected = Goal.where(accept: nil, user_id: session[:user_id]).order("updated_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goals }
    end
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goal = Goal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/new
  # GET /goals/new.json
  def new
    @goal = Goal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/1/edit
  def edit
    @goal = Goal.find(params[:id])
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(params[:goal])

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render json: @goal, status: :created, location: @goal }
      else
        format.html { render action: "new" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goals/1
  # PUT /goals/1.json
  def update
    @goal = Goal.find(params[:id])

    respond_to do |format|
      if @goal.update_attributes(params[:goal])
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <% all_users = User.all %>
    <% user_items = all_users.map { |c| [ c.first_name + " " + c.last_name, c.id ] } %>
    <% if params[:action] == "new" %>
        <%= f.select :user_id, user_items, :selected=>session[:user_id] %>
    <% else %>
        <%= f.select :user_id, user_items, :placeholder=>'Test' %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :challenger_id %><br />
    <% if params[:action] == "new" %>
        <%= f.select :challenger_id, user_items, :selected=>session[:user_id] %>
    <% else %>
        <%= f.select :challenger_id, user_items %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :num_of_steps %><br />
    <%= f.number_field :num_of_steps %>
  </div>
  <div class="field">
    <%= f.label :num_of_steps_so_far %><br />
    <%= f.number_field :num_of_steps_so_far %>
  </div>
  <div class="field">
    <%= 
    #f.label :accept 
    %><!--<br />-->
    <%=
    # f.number_field :accept 
    %>
    

    <%=  f.radio_button 'accept', 1 %>
    <%= f.label :accept, "Accept" %>
    <%=  f.radio_button 'accept', 0 %>
    <%= f.label :accept, "Reject" %>
    
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<div class="container">
	<h4>Editing goal</h4>
	
	<%= render 'form' %>
	
	<%= link_to 'Show', @goal %> |
	<%= link_to 'Back', goals_path %>

</div>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "container">
	<!--<div id="feedPageHeader">
		<h4>Feeds</h4>

	</div>-->
	<div id="feedPageNewGoalBtn">
		<button type="button" class="btn btn-success btn-xs"> 
		<%= link_to 'New Goal', new_goal_path, :class=>'btnlink-white' %>
		</button>
	</div>
	<div>
    	<ul class="nav nav-tabs">
        	<li class="active"><a href="#home" data-toggle="tab" class="feedPageTab">Feeds</a></li>
        	<li>
        		<a href="#profile" data-toggle="tab" class="feedPageTab">
        			<span class="glyphicon glyphicon-bullhorn"> 
        				<span id="feedPageNumGoalsToAcceptOrReject"><%=Goal.where(accept: nil, user_id: session[:user_id]).count%></span>
        			</span>
        		</a>
        	</li>
      	</ul>
    </div>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade in active" id="home">  
  <% @goals_acceptedOrRejected.each do |goal| %>
      <%
         #link_to 'Show', goal %>
      <%
         #link_to 'Edit', edit_goal_path(goal) %>
      <%
         #link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %>

      <% if goal.accept == 1 %>
      	<% if goal.num_of_steps_so_far >= goal.num_of_steps %>
        	<div class="row pretty-row finished-row">
        <% else %>
        	<div class="row pretty-row inprogress-row">
        <% end %>
      <% elsif goal.accept == 0 %>
      	<div class="row pretty-row rejected-row">
      <% else %>
        <div class="row pretty-row">
      <% end %>
      	<table>
      	<tr><td>
       <!-- <div style="display:inline-block; float:left; border:3px solid black;"> -->
			<% if goal.user.image? %>
        		<%= link_to image_tag(goal.user.image_url, :class => 'profile-image img-circle'), 
            		goal.user, :class=>'profile-image-link' %>
        	<% else %>
				<%= link_to image_tag('nopic.jpg', :class => 'profile-image img-circle'), 
            		goal.user, :class=>'profile-image-link' %>
     	  	<% end %>
          
        <!--</div>-->
        </td><td style="vertical-align:text-top; padding:5px;">
       <!-- <div style="display:inline-block; width:300px; border:3px solid red;"> -->
            <strong>"<%= link_to goal.name, edit_goal_path(goal) %>"</strong>
            <% if goal.accept == 1 %>
                <br /><span style="font-size:150%"><%=goal.num_steps_so_far_formatted%></span>
          		<strong>of goal <%= goal.num_steps_formatted%> steps</strong>
            <% end %>
          
          <br />
          <% if goal.user_id == goal.challenger_id %>
            <!-- Individual challenge -->
          <% else %>
            <%=
            #User.find_by_id(goal.challenger_id).first_name
            %><!--'s challenge -->
          <% end %>
          <!--<br />-->
          <% if goal.accept == 1 %>
            <% if goal.num_of_steps_so_far >= goal.num_of_steps %>
                Goals Completed!
            <% else %>
                In Progress
            <% end %>
          <% elsif goal.accept == 0 %>
            Goal Rejected!
          <% else %>
            <button type = "button" class="btn btn-primary btn-xs">
                  <%= link_to "Accept",
                    { :controller => 'goalaccepter',
                      :action => 'accept_goal',
                      :goal_id => goal.id,
                      :accept => 1 },
                    :method => 'POST',
                    :class=> 'btnlink-white'
                %>
            </button>
            <button type = "button" class="btn btn-danger btn-xs">
                <%= link_to "Reject",
                    { :controller => 'goalaccepter',
                      :action => 'accept_goal',
                      :goal_id => goal.id,
                      :accept => 0 },
                    :method => 'POST',
                    :class=> 'btnlink-white'
                %>
            </button>
          <% end %>
          
            - <%= time_ago_in_words(goal.updated_at) %> ago by 
            <% if goal.user_id == session[:user_id] %>
            	you
            <%else%>
            	<%=goal.user.first_name%> <%=goal.user.last_name%>
           	<%end%> 
       <!-- </div> -->
        </td></tr>
        </table>
      </div>
  <% end %>
  </div>
  <div class="tab-pane fade" id="profile">
  <% @goals_notYetAcceptedOrRejected.each do |goal| %>
      <%
         #link_to 'Show', goal %>
      <%
         #link_to 'Edit', edit_goal_path(goal) %>
      <%
         #link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %>

      <% if goal.accept == 1 %>
      	<% if goal.num_of_steps_so_far >= goal.num_of_steps %>
        	<div class="row pretty-row finished-row">
        <% else %>
        	<div class="row pretty-row inprogress-row">
        <% end %>
      <% elsif goal.accept == 0 %>
      	<div class="row pretty-row rejected-row">
      <% else %>
        <div class="row pretty-row">
      <% end %>
      	<table>
      	<tr><td>
       <!-- <div style="display:inline-block; float:left; border:3px solid black;"> -->
			<% if goal.user.image? %>
        		<%= link_to image_tag(goal.user.image_url, :class => 'profile-image img-circle'), 
            		goal.user, :class=>'profile-image-link' %>
        	<% else %>
				<%= link_to image_tag('nopic.jpg', :class => 'profile-image img-circle'), 
            		goal.user, :class=>'profile-image-link' %>
     	  	<% end %>
          
        <!--</div>-->
        </td><td style="vertical-align:text-top; padding:5px;">
       <!-- <div style="display:inline-block; width:300px; border:3px solid red;"> -->
            <strong>"<%= link_to goal.name, edit_goal_path(goal) %>"</strong>
            <% if goal.accept == 1 %>
                <% if goal.num_of_steps_so_far.is_a? Integer %>
                    (<%=goal.num_steps_so_far_formatted%>/<%= goal.num_steps_formatted%> steps)
                <% else %>
                    (0/<%=goal.num_steps_formatted%> steps)
                <% end %>
            <% end %>
          <br />
          
          <% if goal.user_id == goal.challenger_id %>
            <!-- Individual challenge -->
          <% else %>
            <%=
            #User.find_by_id(goal.challenger_id).first_name
            %><!--'s challenge -->
          <% end %>
          <!--<br />-->
          <% if goal.accept == 1 %>
            <% if goal.num_of_steps_so_far >= goal.num_of_steps %>
                Goals Completed!
            <% else %>
                In Progress
            <% end %>
          <% elsif goal.accept == 0 %>
            Goal Rejected!
          <% else %>
            <button type = "button" class="btn btn-primary btn-xs">
                  <%= link_to "Accept",
                    { :controller => 'goalaccepter',
                      :action => 'accept_goal',
                      :goal_id => goal.id,
                      :accept => 1 },
                    :method => 'POST',
                    :class=> 'btnlink-white'
                %>
            </button>
            <button type = "button" class="btn btn-danger btn-xs">
                <%= link_to "Reject",
                    { :controller => 'goalaccepter',
                      :action => 'accept_goal',
                      :goal_id => goal.id,
                      :accept => 0 },
                    :method => 'POST',
                    :class=> 'btnlink-white'
                %>
            </button>
          <% end %>
          
            - <%= time_ago_in_words(goal.updated_at) %> ago by 
            <% if goal.user_id == session[:user_id] %>
            	you
            <%else%>
            	<%=goal.user.first_name%> <%=goal.user.last_name%>
           	<%end%> 
       <!-- </div> -->
        </td></tr>
        </table>
      </div>
  <% end %>
  </div>
</div>
  
</div>

app/views/goals/new.html.erb
<div class="container">
	<h4>New goal</h4>
	
	<%= render 'form' %>
	<%= link_to 'Back', goals_path %>
</div>

app/views/goals/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>
	
	<p>
	  <b>User:</b>
	  <%= @goal.user_id %>
	</p>
	
	<p>
	  <b>Challenger:</b>
	  <%= @goal.challenger_id %>
	</p>
	
	<p>
	  <b>Name:</b>
	  <%= @goal.name %>
	</p>
	
	<p>
	  <b>Num of steps:</b>
	  <%= @goal.num_of_steps %>
	</p>
	
	<p>
	  <b>Num of steps so far:</b>
	  <%= @goal.num_of_steps_so_far %>
	</p>
	
	<p>
	  <b>Accept:</b>
	  <%= @goal.accept %>
	</p>
	
	
	<%= link_to 'Edit', edit_goal_path(@goal) %> |
	<%= link_to 'Back', goals_path %>
</div>